<?php
/**
 * Critical-path tests for IAWM_Auth — canonical message format and
 * the signature roundtrip exercised by `guard()`.
 *
 * `canonical_query` is a private helper, so we exercise its behaviour
 * via Reflection — this is intentional. Treating it as a black box
 * through `build_message()` would fold its determinism into a much
 * larger assertion that fails for the wrong reason if any of the other
 * six message fields changes. A direct test pins the contract.
 *
 * The full roundtrip test (`testSignatureRoundtrip`) exercises the
 * public entry point `guard_read()` end-to-end with a real signature.
 *
 * @package IA_Webmaster_Bridge\Tests
 */

/**
 * @covers IAWM_Auth
 */
final class IAWM_Test_Auth extends IAWM_Test_Case {

	/**
	 * Same inputs (method, route, body, ts, nonce) must yield byte-for-byte
	 * the same canonical message — the foundation of HMAC determinism.
	 *
	 * @return void
	 */
	public function testCanonicalMessageDeterministic() {
		$request_a = new WP_REST_Request( 'POST', '/ia-webmaster/v1/ping' );
		$request_a->set_body( '{"hello":"world"}' );
		$request_a->set_query_params( array( 'a' => 1, 'b' => 2 ) );

		$request_b = new WP_REST_Request( 'POST', '/ia-webmaster/v1/ping' );
		$request_b->set_body( '{"hello":"world"}' );
		$request_b->set_query_params( array( 'a' => 1, 'b' => 2 ) );

		$ts    = '1700000000';
		$nonce = 'nonce-12345';

		$msg_a = IAWM_Auth::build_message( $request_a, $ts, $nonce );
		$msg_b = IAWM_Auth::build_message( $request_b, $ts, $nonce );

		$this->assertSame( $msg_a, $msg_b, 'Identical inputs must produce identical canonical messages' );

		// Sanity: the canonical message has 7 newline-separated fields.
		$this->assertCount( 7, explode( "\n", $msg_a ) );
	}

	/**
	 * `canonical_query` must sort by key so the order in which params
	 * were placed in the URL has no effect on the signature.
	 *
	 * Uses Reflection because the method is private — that's a
	 * deliberate part of the module's API surface.
	 *
	 * @return void
	 */
	public function testCanonicalQuerySorts() {
		$method = new ReflectionMethod( 'IAWM_Auth', 'canonical_query' );
		$method->setAccessible( true );

		$out = $method->invoke( null, array( 'b' => 1, 'a' => 2 ) );
		$this->assertSame( 'a=2&b=1', $out );

		// And the inverse insertion order must yield the same canonical form.
		$out_2 = $method->invoke( null, array( 'a' => 2, 'b' => 1 ) );
		$this->assertSame( 'a=2&b=1', $out_2 );

		// Empty array is the empty string by contract.
		$this->assertSame( '', $method->invoke( null, array() ) );
	}

	/**
	 * Build a signed request with a real key, then pass it through the
	 * full `guard()` pipeline. A correctly-signed request must pass.
	 *
	 * The test exercises everything `guard()` touches:
	 *   - the HTTPS pre-check (skipped when IAWM_REQUIRE_HTTPS is undefined),
	 *   - the IP allow-list (empty by default = allow all),
	 *   - credential resolution by key id,
	 *   - timestamp + nonce checks,
	 *   - HMAC verification,
	 *   - scope check (legacy / fully-scoped key here),
	 *   - the kill switch (off by default).
	 *
	 * @return void
	 */
	public function testSignatureRoundtrip() {
		// Provision a key directly into the credentials store. We avoid
		// IAWM_Settings::create_credentials() here because its secret is
		// generated by random_bytes and we need to know the cleartext to
		// sign with.
		$key_id = 'iawm_test01';
		$secret = str_repeat( 'ab', 32 );
		update_option(
			IAWM_Settings::OPTION_CREDENTIALS,
			array(
				$key_id => array(
					'secret'       => $secret,
					'label'        => 'Test key',
					'created_at'   => gmdate( 'c' ),
					'last_used_at' => null,
				),
			)
		);

		// Build a request as the MCP gateway would.
		$route = '/ia-webmaster/v1/status';
		$body  = '{"probe":1}';
		$ts    = (string) time();
		$nonce = bin2hex( random_bytes( 16 ) );

		$request = new WP_REST_Request( 'POST', $route );
		$request->set_body( $body );

		$message   = IAWM_Auth::build_message( $request, $ts, $nonce );
		$signature = hash_hmac( 'sha256', $message, $secret );

		$request->set_header( 'X-IAWM-Key', $key_id );
		$request->set_header( 'X-IAWM-Timestamp', $ts );
		$request->set_header( 'X-IAWM-Nonce', $nonce );
		$request->set_header( 'X-IAWM-Signature', $signature );

		$result = IAWM_Auth::guard( $request, false );

		$this->assertTrue( $result, 'A correctly-signed request must pass guard()' );

		// Replaying the very same request must now fail on the nonce
		// check — defence in depth confirmation for the test, the
		// signature is identical but the nonce has been consumed.
		$replay = IAWM_Auth::guard( $request, false );
		$this->assertInstanceOf( WP_Error::class, $replay, 'Replay must be refused on nonce reuse' );
		$this->assertSame( 'iawm_unauthorized', $replay->get_error_code() );
	}
}
